### ISSUE TITLE
Braintree support

### ISSUE THREAD

**Issue by iadj** [yii2mod/yii2-cashier#1]
This package looks really good! Any plans for porting over Braintree support?

**Comment by igor-chepurnoi** [comment]
Hi, thanks.
I think we can do it on this week or maybe on the next week.

**Comment by igor-chepurnoi** [comment]
@iadj https://github.com/yii2mod/yii2-braintree

**Comment by iadj** [comment]
@igor-chepurnoi Awesome! Is it possible to use both in the same project, so users can pick whether they want to pay with CC (Stripe `yii2-cashier`) or Paypal (Braintree `yii2-braintree`)?
I noticed that both subscription methods are `$user->newSubscription('main', 'monthly')->create($creditCardToken);`

**Comment by igor-chepurnoi** [comment]
@iadj it's good idea, but right now we don't have time for this. PR are welcome :)
