### ISSUE TITLE
Use of undefined constant DOMPDF_TEMP_DIR - assumed 'DOMPDF_TEMP_DIR'

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-cashier#2]
Any ideas?

**Comment by igor-chepurnoi** [comment]
Hi, I update composer.json, can you update this package and try again?

**Before update, set in your composer.json dev-master as version for this package**

**Comment by robov** [comment]
"yii2mod/yii2-cashier": "dev-master",
        "dompdf/dompdf" : "*"

Class 'DOMPDF' not found

1. in /home/mxcom05/public_html/digitalsentinel/pdfsentinel.com/dev/vendor/yii2mod/yii2-cashier/Invoice.php at line 268
25926026126226326426526626726826927027127227327427527627

**Comment by igor-chepurnoi** [comment]
dompdf/dompdf will be installed with cashier, https://github.com/yii2mod/yii2-cashier/blob/master/composer.json#L22

**Comment by igor-chepurnoi** [comment]
Can you paste here your code for reproduce this issue?

**Comment by robov** [comment]
I copied your code and pressed download
then this error shows up

**Comment by igor-chepurnoi** [comment]
ok, I try to fix it.

**Comment by igor-chepurnoi** [comment]
Try to update package. I fix this issue

**Comment by robov** [comment]
working now... brilliant
