### ISSUE TITLE
Fields Description Receipt_number empty

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-cashier#3]
When I do this:
$user->newSubscription('main', 'monthly')->create($creditCardToken, [
    'description' => 'Customer for test@example.com'
]);

and I show the invoices with your code, then the fields description and receipt_number are both empty

**Comment by igor-chepurnoi** [comment]
`description` field used for customer object in stripe, not for invoices

**Comment by igor-chepurnoi** [comment]
https://stripe.com/docs/api#create_customer-description
