### ISSUE TITLE
how to get $creditCardToken 

### ISSUE THREAD

**Issue by vickysw** [yii2mod/yii2-cashier#7]
$user = User::findOne(1);

$user->newSubscription('main', 'monthly')->create($creditCardToken);

Can anyone tell me how to get $creditCardToken ?

**Comment by igor-chepurnoi** [comment]
Hi, you can see CashierTest file for example in the tests folder, there are
getToken method

29.09.2017 13:48 пользователь "vickysw" <notifications@github.com> написал:
