### ISSUE TITLE
Unable to subscribe to plan when the customer is deleted from stripe dashboard.

### ISSUE THREAD

**Issue by nomaan-alkurn** [yii2mod/yii2-cashier#9]
Hi,

Thanks for the extension. Facing an issue when the customer is deleted from stripe dashboard. Receiving the following error when I try to create a new subscribe as it is not reflected in our database:
Call to a member function create() on null in /home/alkurnw1/public_html/clients/service-for-you-app/vendor/yii2mod/yii2-cashier/SubscriptionBuilder.php:179

We need to check the customer exist at stripe dashboard in getStripeCustomer function at this line https://github.com/yii2mod/yii2-cashier/blob/ddd8cf8bd077d75c799d1114355ae47523c34070/SubscriptionBuilder.php#L212

**Comment by igor-chepurnoi** [comment]
Hi, thanks for the issue. I will check it on this week.

**Comment by igor-chepurnoi** [comment]
Also, you can create PR to resolve this issue.

**Comment by nomaan-alkurn** [comment]
Hi @igor-chepurnoi , 
I will also check at my end and create a PR.

**Comment by igor-chepurnoi** [comment]
Hi @nomaan-alkurn ,
Thanks!
